name       : kwallet
version    : 5.74.0
release    : 43
source     :
    - https://cdn.download.kde.org/stable/frameworks/5.74/kwallet-5.74.0.tar.xz : 7abcf5230c7112628d4b1ac37648ab2d7fb147e4fda61e7aa0fd0da1d59cb0a1
homepage   : https://community.kde.org/Frameworks
license    : LGPL-2.1-or-later
component  : desktop.library
optimize   : lto
summary    : Safe desktop-wide storage for passwords
description: |
    This framework contains two main components:
    * Interface to KWallet, the safe desktop-wide storage for passwords on KDE work spaces.
    * The kwalletd used to safely store the passwords on KDE work spaces.
builddeps  :
    - pkgconfig(Qt5UiTools)
    - extra-cmake-modules
    - gpgme-qt-devel
    - kconfigwidgets-devel
    - kdbusaddons-devel
    - kdoctools-devel
    - ki18n-devel
    - kiconthemes-devel
    - knotifications-devel
    - kservice-devel
    - kwindowsystem-devel
    - libgcrypt-devel
setup      : |
    %cmake_ninja -DBUILD_QCH=ON \
                -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
