name       : kwallet
version    : 5.54.0
release    : 24
source     :
    - https://cdn.download.kde.org/stable/frameworks/5.54/kwallet-5.54.0.tar.xz : 62223ca3bbca12da8a06ea1b7827ba9aeb97b75cf8a23ec8944dbc93d4bcd143
license    : LGPL-2.1-or-later
component  : desktop.library
optimize   : lto
summary    : Safe desktop-wide storage for passwords
description: |
    This framework contains two main components:
    * Interface to KWallet, the safe desktop-wide storage for passwords on KDE work spaces.
    * The kwalletd used to safely store the passwords on KDE work spaces.
builddeps  :
    - pkgconfig(Qt5UiTools)
    - extra-cmake-modules
    - gpgme-qt-devel
    - kconfig-devel
    - kconfigwidgets-devel
    - kcoreaddons-devel
    - kdbusaddons-devel
    - kdoctools-devel
    - ki18n-devel
    - kiconthemes-devel
    - knotifications-devel
    - kservice-devel
    - kwidgetsaddons-devel
    - kwindowsystem-devel
    - libassuan-devel
    - libgcrypt-devel
setup      : |
    %cmake_ninja -DBUILD_QCH=ON \
                -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
