name       : kwallet
version    : 5.78.0
release    : 49
source     :
    - https://cdn.download.kde.org/stable/frameworks/5.78/kwallet-5.78.0.tar.xz : 9730997f28ca4e55b015a5d76adcb1200d3e26ec21af9f1a598ce3e4532b16a9
homepage   : https://community.kde.org/Frameworks
license    :
    - BSD-3-Clause
    - LGPL-2.0-only
    - LGPL-2.0-or-later
    - LGPL-3.0-or-later
    - LGPL-2.1-or-later
component  : desktop.library
summary    : Safe desktop-wide storage for passwords
description: |
    This framework contains two main components:
    * Interface to KWallet, the safe desktop-wide storage for passwords on KDE work spaces.
    * The kwalletd used to safely store the passwords on KDE work spaces.
optimize   : lto
builddeps  :
    - pkgconfig(libgcrypt)
    - gpgme-qt-devel
    - kconfigwidgets-devel
    - kdbusaddons-devel
    - kdoctools-devel
    - ki18n-devel
    - knotifications-devel
    - kservice-devel
    - kwidgetsaddons-devel
    - kwindowsystem-devel
setup      : |
    %cmake_ninja -DBUILD_QCH=ON \
                -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
