name       : kwallet
version    : 5.32.0
release    : 3
source     :
    - http://download.kde.org/stable/frameworks/5.32/kwallet-5.32.0.tar.xz : aa97ed3255bb6ae49f663df41a6e07597cd2c7d8af1e6b455f2f4d468d254c5f
license    : LGPL-2.1
component  : desktop.library
summary    : Safe desktop-wide storage for passwords
description: |
    This framework contains two main components:
    * Interface to KWallet, the safe desktop-wide storage for passwords on KDE work spaces.
    * The kwalletd used to safely store the passwords on KDE work spaces.
builddeps  :
    - pkgconfig(gl)
    - pkgconfig(Qt5Core)
    - extra-cmake-modules
    - kconfig-devel
    - kconfigwidgets-devel
    - kcoreaddons-devel
    - kdbusaddons-devel
    - ki18n-devel
    - kiconthemes-devel
    - knotifications-devel
    - kservice-devel
    - kwidgetsaddons-devel
    - kwindowsystem-devel
    - libassuan-devel
setup      : |
    %cmake -DBUILD_TESTING=FALSE .
build      : |
    %make
install    : |
    %make_install
