name       : kwallet
version    : 5.28.0
release    : 2
source     :
    - http://download.kde.org/stable/frameworks/5.28/kwallet-5.28.0.tar.xz : 3513813399f214e855ead5f12147a11e39d3ccd7b79c2ede2a5b0fcfe5ae4558
license    : LGPL-2.1
component  : desktop.library
summary    : Safe desktop-wide storage for passwords
description: |
    This framework contains two main components:
    * Interface to KWallet, the safe desktop-wide storage for passwords on KDE work spaces.
    * The kwalletd used to safely store the passwords on KDE work spaces.
builddeps  :
    - pkgconfig(gl)
    - pkgconfig(Qt5Core)
    - extra-cmake-modules
    - gpgme-devel
    - kconfig-devel
    - kconfigwidgets-devel
    - kcoreaddons-devel
    - kdbusaddons-devel
    - ki18n-devel
    - kiconthemes-devel
    - knotifications-devel
    - kservice-devel
    - kwidgetsaddons-devel
    - kwindowsystem-devel
    - libassuan-devel
setup      : |
    %cmake -DBUILD_TESTING=FALSE .
build      : |
    %make
install    : |
    %make_install
