name       : kwallet
version    : 5.79.0
release    : 50
source     :
    - https://cdn.download.kde.org/stable/frameworks/5.79/kwallet-5.79.0.tar.xz : 77b8a16ffdfda08f018a1c58e24758af37405cdbf9b096236318f90c849d2ce2
homepage   : https://community.kde.org/Frameworks
license    :
    - BSD-3-Clause
    - LGPL-2.0-only
    - LGPL-2.0-or-later
    - LGPL-3.0-or-later
    - LGPL-2.1-or-later
component  : desktop.library
summary    : Safe desktop-wide storage for passwords
description: |
    This framework contains two main components:
    * Interface to KWallet, the safe desktop-wide storage for passwords on KDE work spaces.
    * The kwalletd used to safely store the passwords on KDE work spaces.
optimize   : lto
builddeps  :
    - pkgconfig(libgcrypt)
    - gpgme-qt-devel
    - kconfigwidgets-devel
    - kdbusaddons-devel
    - kdoctools-devel
    - ki18n-devel
    - knotifications-devel
    - kservice-devel
    - kwidgetsaddons-devel
    - kwindowsystem-devel
setup      : |
    %cmake_ninja -DBUILD_QCH=ON \
                -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
