name       : kwallet
version    : 5.60.0
release    : 30
source     :
    - https://cdn.download.kde.org/stable/frameworks/5.60/kwallet-5.60.0.tar.xz : 2ac2186dd7d004b6740cb14e7651ddcb7d74390acb382c9d55874f3a03a8111d
license    : LGPL-2.1-or-later
component  : desktop.library
optimize   : lto
summary    : Safe desktop-wide storage for passwords
description: |
    This framework contains two main components:
    * Interface to KWallet, the safe desktop-wide storage for passwords on KDE work spaces.
    * The kwalletd used to safely store the passwords on KDE work spaces.
builddeps  :
    - pkgconfig(Qt5UiTools)
    - extra-cmake-modules
    - gpgme-qt-devel
    - kconfigwidgets-devel
    - kdbusaddons-devel
    - kdoctools-devel
    - ki18n-devel
    - kiconthemes-devel
    - knotifications-devel
    - kservice-devel
    - kwindowsystem-devel
    - libassuan-devel
    - libgcrypt-devel
setup      : |
    %cmake_ninja -DBUILD_QCH=ON \
                -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
