name       : kwallet
version    : 5.42.0
release    : 11
source     :
    - https://cdn.download.kde.org/stable/frameworks/5.42/kwallet-5.42.0.tar.xz : 76a99bca363a314b2c889c562cdab93d83b136cce4e2d338b02eeb91cad963cf
license    : LGPL-2.1
component  : desktop.library
optimize   : lto
summary    : Safe desktop-wide storage for passwords
description: |
    This framework contains two main components:
    * Interface to KWallet, the safe desktop-wide storage for passwords on KDE work spaces.
    * The kwalletd used to safely store the passwords on KDE work spaces.
builddeps  :
    - pkgconfig(gl)
    - pkgconfig(Qt5UiTools)
    - extra-cmake-modules
    - gpgme-qt-devel
    - kconfig-devel
    - kconfigwidgets-devel
    - kcoreaddons-devel
    - kdbusaddons-devel
    - kdoctools-devel
    - ki18n-devel
    - kiconthemes-devel
    - knotifications-devel
    - kservice-devel
    - kwidgetsaddons-devel
    - kwindowsystem-devel
    - libassuan-devel
setup      : |
    %cmake -DBUILD_QCH=ON .
build      : |
    %make
install    : |
    %make_install
