name       : kwallet
version    : 5.36.0
release    : 6
source     :
    - https://download.kde.org/stable/frameworks/5.36/kwallet-5.36.0.tar.xz : 8782caeb8d75da67a84c8eddf1d28af19fb01ffc0bbf7a35c0240e22519ccabb
license    : LGPL-2.1
component  : desktop.library
summary    : Safe desktop-wide storage for passwords
description: |
    This framework contains two main components:
    * Interface to KWallet, the safe desktop-wide storage for passwords on KDE work spaces.
    * The kwalletd used to safely store the passwords on KDE work spaces.
builddeps  :
    - pkgconfig(gl)
    - pkgconfig(Qt5Core)
    - extra-cmake-modules
    - gpgme-qt-devel
    - kconfig-devel
    - kconfigwidgets-devel
    - kcoreaddons-devel
    - kdbusaddons-devel
    - ki18n-devel
    - kiconthemes-devel
    - knotifications-devel
    - kservice-devel
    - kwidgetsaddons-devel
    - kwindowsystem-devel
    - libassuan-devel
setup      : |
    %cmake -DBUILD_TESTING=FALSE .
build      : |
    %make
install    : |
    %make_install
