name       : kwallet
version    : 5.89.0
release    : 59
source     :
    - https://cdn.download.kde.org/stable/frameworks/5.89/kwallet-5.89.0.tar.xz : 3034db91605f287460420e4ce66bc8fa5f09076c8dfb2ed1895616aab422c3fb
homepage   : https://community.kde.org/Frameworks
license    :
    - BSD-3-Clause
    - LGPL-2.0-only
    - LGPL-2.0-or-later
    - LGPL-3.0-or-later
    - LGPL-2.1-or-later
component  : desktop.library
summary    : Safe desktop-wide storage for passwords
description: |
    This framework contains two main components:
    * Interface to KWallet, the safe desktop-wide storage for passwords on KDE work spaces.
    * The kwalletd used to safely store the passwords on KDE work spaces.
optimize   : lto
builddeps  :
    - pkgconfig(libgcrypt)
    - gpgme-qt-devel
    - kconfigwidgets-devel
    - kdbusaddons-devel
    - kdoctools-devel
    - ki18n-devel
    - knotifications-devel
    - kservice-devel
    - kwidgetsaddons-devel
    - kwindowsystem-devel
setup      : |
    %cmake_ninja -DBUILD_QCH=ON \
                -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
